sylius_ui:
    events:
        sylius.shop.layout.topbar:
            blocks:
                currency_switcher:
                    template: "@MonsieurBizSyliusCaseStudyPlugin/Shop/Layout/Topbar/_caseStudyLink.html.twig"
                    priority: 15
