services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    MonsieurBiz\SyliusCaseStudyPlugin\:
        resource: '../../*'
        exclude: '../../{Entity,Migrations}'

    MonsieurBiz\SyliusCaseStudyPlugin\Controller\:
        resource: '../../Controller'
        tags: [ 'controller.service_arguments' ]

